import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Clifford.module.css'

export default function Home() {
  // Declare a new state variable, which we'll call "count"
  const [count, setCount] = useState(0);
  const [cookie, setCookie] = useState(0);

  const countHandle = () => {
    setCount(count + 1)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
        <meta name="format-detection" content="telephone=no" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className={styles.main} onClick={countHandle}>
        <div className={styles.intro}>
          <figure className={styles.logo}>
            <Image src="/logo.png" alt="Clifford The Big Red Dog" width={600} height={338} />
            {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
          </figure>
          <div className={styles.counter}>{count}</div>
        </div>
        {/* <div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> */}
        <div className={styles.clifford}>
          <Image src="/clifford.png" alt="Clifford" width={300} height={300} layout="fixed" />
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
